[project]
name = "ratel-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7, <4.0"
dependencies = []

[project.scripts]
ratel-helper = "ratel_helper.main:app"
