[project]
name = "ratel-helper"
version = "0.2.0"
description = "Helper tools for building and running Ratel"
readme = "README.md"
requires-python = ">=3.7, <4.0"
dependencies = []

[tool.uv.build-backend]
includes = ["src/ratel_helper"]
module-name = 'ratel_helper'

[project.scripts]
ratel-helper = "ratel_helper.main:app"
